//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTS.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public long LotId { get; set; }
        public Nullable<long> AreaId { get; set; }
        public string LotDescription { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> Sqm { get; set; }
        public Nullable<long> Block { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
